name: Awesome Inc
short_description: Create and grow high tech startups.
description: Create and grow high tech startups.  Awesome Inc offers an accelerator, coding school, and a coworking space for entrepreneurs.
permalink: pretty
relative_permalinks: false
include: [_data]
sass:
  sass_dir: _scss
  # style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - node_modules